script
global a, b, obj_prototype

a = [ 1, 3, "23", 4.2 ]
b = { pouet:a, coin: a[2] }

print("b.coin=",b.coin,"\n")

function _clone(x) asm getmem -1 clone setmem -1 end return x end

function new(cls)
	local ret
	ret = _clone(cls)
	ret._cls = cls
	ret._new(ret)
	return ret
end

obj_prototype = {
	_new: function(self) self.pouet="hello, world\n" end,
	get_msg: function(self) return self.pouet end
}

a = new(obj_prototype)

print("obj says : ", a.get_msg(a),"\n")

end
