script


global a,b,c,d,e

function newArray() asm arrayNew push 1 ret 0 end end
function newStruc() asm mapNew push 1 ret 0 end end

function genDecimator(y)
	return function(x) return x/y end
end

e = newStruc()

e.foo = newArray()
e.foo[0] = newStruc()
e.foo[0].bla=newStruc()
e.foo[0].bla.foo = newArray()

e.foo[0].bla.foo[0+3] = 3

print(e.foo[0],"\n",e.foo[0].bla.foo[0+3],"\n")

e.decim = genDecimator(10)
e.septim = genDecimator(7)

#a = 1+1+1
#b = a*3+3
#c = 4+b*2
#d = a*1.0/b*c-3*2+1
#
#
#
##f.test_array_of[1]=w
#
##w.wobble = "hop hop"
##w.wabble = f.test_array[0]
#
##print "w.wabble = ",w.wabble,"\n"
#
#print "a = ",a,"\n"
#print "b = ",b,"\n"
#print "c = ",c,"\n"
#print "a*1.0/b*c = ",a*1.0/b*c,"\n"
#print "\n d = ",d,"\n\n"

function hello (a,b)
	local z,zz,zzz
	zz=3
	zzz=0
	#z=e.foo[zzz].bla.foo[zz]
	#z= zz+zzz/0
	z = 3*(5-z)
	print("Hello, ",a," & ",b,"\n")
	return b
end

hello("bla","pouet")

hello(e.decim(6106),e.septim(6106))

function genHello(a,b)
	local x,y
	x=a
	y=b
	return function() hello(x,y) return genDecimator(9) end
end

a = genHello("Toto","Pouet")

b = a()
print("b(999) = ",b(999),"\n")

#b("foobar")

#function fact(n)
#	#asm getmem -1 dec SZ jmp @skip push 1 ret 0 skip: nop end
#	asm nop end
#	if n<=1 then
#		return 1
#		asm ret 0 end
#	end
#	return n*fact(n-1)
#end
#
#c="yop"
#d="bla"
#
#hello(c,d)
#
#print "1 and 1 = ",1 and 1,"\n"
#print "23 = 42 ? ",23=42,"\n"
#print "23 != 42 ? ",23!=42,"\n"
#print "23 < 42 ? ",23<42,"\n"
#print "23 < 42 and 0 ? ",23<42 and 0,"\n"
#print "23 < 42 and not 0 ? ",23<42 and not 0,"\n"
#print "\n"
#a=1
#while a!=20 do
#	print "La factorielle de ",a,"\test : ",fact(a),"\n"
#	a=a+1
#end
#
#asm nop end
end

#language
#	hello ::= "hello" ("," <world> | <foobar> ).
#	world ::= "world".
#	foobar = /[a-zA-Z]*/ <world>.
#end
#
#plug hello into _start
#
#compile hello script
#	print "hello\n"
#	asm compileStateDown end
#end
#
#compile world script print "world\n" asm compileStateNext end end
#compile foobar script print "foobar\n" asm compileStateNext end end
#
##asm push "hello foobarish world" compileString end


